### ISSUE TITLE
Image contains, and runs, PHP 8

### ISSUE THREAD

**Issue by cooperaj** [linuxserver/docker-mastodon#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The image, as it relies on the baseimage contains PHP8. It also runs it as PHP-FPM using (on my machine) 23MB of RAM. I don't believe it's needed at all for Mastodon so should probably be removed/turned off?

------------------------------

## Expected Behavior
Mastodon runs with only the required services.

## Current Behavior
Mastodon runs with PHP-FPM sat there doing nothing.

## Steps to Reproduce

1. Run the image

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** x86_64
**How docker service was installed:**

Offical image

## Command used to create docker container (run/create/compose/screenshot)

Running under Dokku using a custom derived image
```
FROM lscr.io/linuxserver/mastodon:4.0.0-develop

COPY root/ /
COPY nginx.conf.sigil /
```

**Comment by thespad** [comment]
It's because our nginx baseimage includes PHP. I'll do a PR to disable the fpm service as it's not used by Mastodon.
