### ISSUE TITLE
Suggestion to rename config volume

### ISSUE THREAD

**Issue by TiMESPLiNTER** [linuxserver/docker-mastodon#13]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
It might make sense to rename the current `config` volume to something like `appdata` as the volume contains way more than just the config. Also cached and originally uploaded files are stored in this directory not just config for Mastodon itself. Hence the volume name is imo a bit misleading.

## Current Behavior
Currently the whole app data is stored in a volume called config.

**Comment by aptalca** [comment]
That's the nomenclature we use as an org, where all the persistent data is stored in the `/config` folder (with very few exceptions where there may be an additional data folder, for media or user data that can go on a remote mount). In this case the user uploaded data is already meant to be stored externally on s3.

In short, the config folder (and the current behavior) is not something we're willing to change as we publish and maintain hundreds of images.

**Comment by TiMESPLiNTER** [comment]
Alright, makes sense. Thanks a lot for the explanation. 👍
