### ISSUE TITLE
Container takes incredibly long time to start once an instance starts amassing files.

### ISSUE THREAD

**Issue by cooperaj** [linuxserver/docker-mastodon#14]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Startup of container should be reasonably quick

## Current Behavior
With 35GB of cache files in the container can take upwards of 2 minutes to start. It appears to hang in the 50-config stage, probably while setting permissions.

## Steps to Reproduce

1. Have a sizable content cache (tested with 35GB)
2. Start container
3. Wait 2+ minutes
4. It starts

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** x86_64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

n/a

## Docker logs

n/a

**Comment by aptalca** [comment]
Ouch, yeah that's the chown operation. We'll have to think about that. We can ignore that location in the chown, which will make it start faster, but if the PUID is ever changed, or the perms are messed with on the host, all media will get 404s. I'll raise ti with the team internally.

In the meantime, you can prune that cache. The gui settings (in v4) allow you to enable auto deletion of cached media older than a configurable number of days.

Out of curiosity, how many users do you have on that instance?

**Comment by thespad** [comment]
Can you try `lspipepr/mastodon:v4.0.2-pkg-4df10d07-pr-15` and see if it improves things?

**Comment by cooperaj** [comment]
So that has made an improvement. It's still not too good though. 50-config took about 25-30 seconds, however 20-permissions from the base image took a good 40-50.

Looking at that on I guess it's a log issue. This isn't a particularly active instance that I now of but it's obviously fairly prolific in what gets put to disk. I dread to thing what a larger instance would be doing.

**Comment by thespad** [comment]
We've updated the image to speed things up a bit, but we'll need an update to the base image to fix the logs being chowned as well, which is the only other potentially large directory.

Ultimately though there's some stuff we still have to chown to make sure the container works OOTB, but in most cases it shouldn't materially impact the startup times.

**Comment by thespad** [comment]
The base has been updated https://github.com/linuxserver/docker-baseimage-alpine-nginx/pull/117 - the current build of the mastodon container should have incorporated the changes, so hopefully startup should be a lot snappier now.

**Comment by cooperaj** [comment]
This seems to be working *a lot* better now. Happy to see it closed
