### ISSUE TITLE
Build in option to use libretranslate

### ISSUE THREAD

**Issue by sdenike** [linuxserver/docker-mastodon#17]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Would love for libtranslate installed on the image such as described here (https://sleeplessbeastie.eu/2022/11/17/how-to-use-libretranslate-with-mastodon/)

### Reason for change

With the growing popularity of Mastodon, it is being adopted worldwide, so the ability to enable translation would be great!

### Proposed code change

Install the libtranslate service which can then be enabled via the docker flags when creating the container.

**Comment by aptalca** [comment]
It looks like Mastodon just needs an ip:port to connect to the translate service, so it would be best to run it in a separate container and input the address into mastodon
