### ISSUE TITLE
[FEAT] Clarification on update procedure

### ISSUE THREAD

**Issue by shiruken** [linuxserver/docker-mastodon#38]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The current [update documentation](https://github.com/linuxserver/docker-mastodon#updating-info) for this project only pertains to updating the Mastodon Docker container. It does not provide information about or instructions for any database migrations required by new versions of Mastodon (see very bottom of the [v4.1.0 changelog](https://github.com/mastodon/mastodon/releases/tag/v4.1.0)). It would be beneficial for users if the update instructions explained that database migrations might be necessary and provided the relevant details. I don't know if it would be feasible to have the container automatically perform the migration after pulling an updated image.

### Reason for change

Improve update instructions to clarify that database migrations need to be performed

**Comment by thespad** [comment]
Database migrations are handled automatically by the container on startup.

**Comment by nogweii** [comment]
Indeed, the two post-upgrade tasks listed in the 4.1.0 changelog are migrations & assets are handled automatically by the container.

### Asset precompilation

That's handled as part of the container image being built, see the [Dockerfile](https://github.com/linuxserver/docker-mastodon/blob/main/Dockerfile#L55). So they are baked into the image and come with by downloading it.

### Migrations

*Every* time the container starts, it runs `rake db:prepare`. (See [`/etc/cont-init.d/50-config` in the container](https://github.com/linuxserver/docker-mastodon/blob/main/root/etc/cont-init.d/50-config#L27).) A little wasteful? Maybe, but checking if you're fully migrated is quick. Much easier for both developers and users of the container than trying to make it smart.

**Comment by thespad** [comment]
Yeah, it takes 5-10 seconds to check if migrations need to be performed on a typical host, but there's no elegant way to detect if it's necessary or not, so it's cleaner and safer to just run it on every startup.

**Comment by shiruken** [comment]
Thanks for the clarifications! I didn't realize that `rake db:prepare` would handle the migrations, I was just looking for the `db:migrate` command.

**Comment by thespad** [comment]
`prepare` is a dual use command - if the database isn't setup yet it will populate it, otherwise it will process any necessary migrations.

**Comment by shiruken** [comment]
I suppose this issue can be closed then. It might still be beneficial to add a blurb about the database migrations being automatically performed in the README to avoid inquiries like my own.
