### ISSUE TITLE
[BUG] White page with logo after startup

### ISSUE THREAD

**Issue by rursache** [linuxserver/docker-mastodon#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running the docker image + cloudflare tunnel to expose the Mastodon server to my domain name. 
Currently all i see is a white page with logo OR a mastodon-colored blank page (depending on incognito/clear cookies/cache)
It was working fine until i checked it today (last week it was fine)

Latest docker image is used.

![mastodon_issue](https://i.imgur.com/UP6JSXK.png)
![mastodon_issue2](https://i.imgur.com/pX9aps4.png)

### Expected Behavior

Actually display the web instance

![working_instance](https://i.imgur.com/IzA4J7i.png)

### Steps To Reproduce

1. Start the container
2. Open the domain.tld
3. ???

### Environment

```markdown
- OS: Ubuntu 22.10 x86_64
- How docker service was installed: `wget -qO - https://get.docker.com | sudo bash - && sudo usermod -aG docker $USER`
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=mastodon \
  --restart always \
  -p 5990:80 \
  -p 5991:443 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Bucharest \
  -e LOCAL_DOMAIN=domain.tld \
  -e REDIS_HOST=192.168.31.100 \
  -e REDIS_PORT=6379 \
  -e DB_HOST=192.168.31.100 \
  -e DB_USER=mastodon \
  -e DB_NAME=mastodon \
  -e DB_PASS=PASS \
  -e DB_PORT=2211 \
  -e ES_ENABLED=false \
  -e SECRET_KEY_BASE=SECRET \
  -e OTP_SECRET=SECRET \
  -e VAPID_PRIVATE_KEY=SECRET \
  -e VAPID_PUBLIC_KEY=SECRET \
  -e SMTP_SERVER=smtp.eu.sparkpostmail.com \
  -e SMTP_PORT=587 \
  -e SMTP_LOGIN=SMTP_Injection \
  -e SMTP_PASSWORD=PASS \
  -e SMTP_FROM_ADDRESS=notifications@mail.domain.tld \
  -e S3_ENABLED=false \
  -e SINGLE_USER_MODE=true \
  -v /home/radu/.mastodon:/config \
  lscr.io/linuxserver/mastodon:latest
```

### Container logs

```bash
https://pastebin.com/Zwp5sRSS
```

**Comment by thespad** [comment]
Nothing obvious stands out in the logs, it might be worth checking the upstream [Issues](https://github.com/mastodon/mastodon/issues/) for anything related to the 4.1.0 upgrade as it's possible something has happened there to cause you problems. I've personally got two instances running on the latest version of the image (both upgrades from 4.0) without any issue so I don't think it's anything specifically wrong on our end.

**Comment by rursache** [comment]
I reached the same conclusion but I had to open an issue here first. Thanks for your time, I'll continue looking for the problem and update this issue

**Comment by rursache** [comment]
Seems like the problem only manifests on macOS on Chrome browser (normal and incognito). Works fine in Windows Chrome, macOS Safari, Windows/macOS Firefox and Chrome Linux.

@thespad I'm not sure where to go from here, should I close the issue?

**Comment by shiruken** [comment]
Are you running this on Cloudflare DNS? Make sure you disable Auto Minify and Rocket Loader on the domain. I encountered similar issues and the auto-minification of Javascript was the culprit.

**Comment by rursache** [comment]
> Are you running this on Cloudflare DNS? Make sure you disable Auto Minify and Rocket Loader on the domain. I encountered similar issues and the auto-minification of Javascript was the culprit.

Indeed I am! Thanks for the tip, gonna change those now and check it up
