### ISSUE TITLE
[BUG] Running behind Apache reverse proxy results in Blocked host

### ISSUE THREAD

**Issue by meghadeep-com** [linuxserver/docker-mastodon#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get a white page with only the favicon loaded and the following error:

`[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: <my WEB_DOMAIN FQDN>`

### Expected Behavior

Mastodon properly loaded

### Steps To Reproduce

1. Use podman to run the image
2. Only forward container port 443 to host port 8443
3. Use apache to reverse proxy to host port 8443

Apache proxy config:
`
ProxyPass / https://127.0.0.1:8443/
ProxyPassReverse / https://127.0.0.1:8443/
SSLProxyEngine on
SSLEngine on
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
`

### Environment

```markdown
- OS:Rocky Linux
- How podman service was installed: distro's packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
podman pod create \
  --name=mastodon-pod \
  -p 8443:443 

podman run -d \
  --pod=mastodon-pod \
  --name=mastodon \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/TZ \
  -e LOCAL_DOMAIN=example.com \
  -e REDIS_HOST=localhost \
  -e REDIS_PORT=6379 \
  -e DB_HOST=localhost \
  -e DB_USER= \
  -e DB_NAME=mastodon \
  -e DB_PASS= \
  -e DB_PORT=5432 \
  -e ES_ENABLED=false \
  -e SECRET_KEY_BASE= \
  -e OTP_SECRET= \
  -e VAPID_PRIVATE_KEY= \
  -e VAPID_PUBLIC_KEY= \
  -e SMTP_SERVER= \
  -e SMTP_PORT= \
  -e SMTP_LOGIN= \
  -e SMTP_PASSWORD= \
  -e SMTP_FROM_ADDRESS=\
  -e S3_ENABLED=false \
  -e WEB_DOMAIN=social.example.com `#optional` \
  -v /path/mastodon/config:/config:Z \
  --restart unless-stopped \
  lscr.io/linuxserver/mastodon:latest
```

### Container logs

```bash
[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: social.example.com
```

**Comment by thespad** [comment]
Does everything work as expected when connecting directly?

We don't test with Apache, but there's no reason in principle it shouldn't work as a reverse proxy for the container.

**Comment by meghadeep-com** [comment]
Nope, even when I directly connect to it, from the host, at https://127.0.0.1:8443/, I also get the same error:

`[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: 127.0.0.1`

**Comment by thespad** [comment]
You won't be able to connect via IP regardless, it has to match the DNS name provided in the config, either the LOCAL_DOMAIN or the WEB_DOMAIN, if specified.

**Comment by meghadeep-com** [comment]
Ahh understood. I have looked up what's going on, and apparently only the allowed domains on config.hosts in production.rb will be allowed, but config.hosts is not mapped in /config in the container, so we cannot modify that directly either.

My Apache config is the following:

ProxyPass / https://127.0.0.1:8443/ 
ProxyPassReverse / https://127.0.0.1:8443/ 
SSLProxyEngine on
SSLProxyCheckPeerCN off 
SSLProxyCheckPeerName off 
SSLEngine on

**Comment by thespad** [comment]
Have you tried setting `TRUSTED_PROXY_IP`? You'll need to check what the source address is for the Apache instance if it's running directly on the host as it might be seen as the docker gateway IP, or it might be the host LAN IP.

**Comment by meghadeep-com** [comment]
Apache is running on the same host that runs the container, and since I am proxying to the host port, I shouldn't need to tweak that since loopback IPs are trusted by default, but trying it now with other internal IPs of the host, will report back what I see!

**Comment by meghadeep-com** [comment]
No change after adding an exhaustive list of the IPs that the host can ever bind to. Still getting the same error.

**Comment by meghadeep-com** [comment]
I was using rootless containers, and thought it might be related to permission issues, but it's not.

When I used root containers (ran using sudo), I still got the same error. With or without using PID and GID variables.

**Comment by meghadeep-com** [comment]
The following Apache config works:

ProxyPass / https://127.0.0.1:8443/
ProxyPassReverse / https://127.0.0.1:8443/
SSLProxyEngine on
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
ProxyPreserveHost On
UseCanonicalName On

**Comment by meghadeep-com** [comment]
For somebody else on the internet stumbling onto this same issue, the following Apache config works well, this also take care of any wss connections that need to be proxied:

ProxyPassReverse / https://127.0.0.1:8443/
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           wss://127.0.0.1:8443/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           https://127.0.0.1:8443/$1 [P,L]
SSLProxyEngine on
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
ProxyPreserveHost On
UseCanonicalName On
