### ISSUE TITLE
[BUG] The page you are looking for isn't here

### ISSUE THREAD

**Issue by LuckyCoders** [linuxserver/docker-mastodon#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Artboard](https://user-images.githubusercontent.com/13001109/235273371-78990733-0198-4b72-816b-0ee80cadf52c.png)

### Expected Behavior

UI don't load at all

### Steps To Reproduce

![Снимок экрана 2023-04-29 в 03 33 30](https://user-images.githubusercontent.com/13001109/235273208-548c798c-ed5d-43d6-b1af-6581e5beffa4.png)

### Environment

- OS: Debian 11 x86-64
- How docker service was installed:
[docker-compose.yml](https://pastebin.com/te4sG3Dn)

**Comment by thespad** [comment]
HTTP 521 is a Cloudflare error code, you need to disable Cloudflare proxying to see the actual error.

**Comment by LuckyCoders** [comment]
> HTTP 521 is a Cloudflare error code, you need to disable Cloudflare proxying to see the actual error.

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/13001109/235329492-55e263f6-6f14-4add-99af-c4472a4cf08c.png">

**Comment by LuckyCoders** [comment]
![Artboard](https://user-images.githubusercontent.com/13001109/235333531-de5b2ae9-c735-45b5-ad95-d715aca8a063.png)
```/packs/js/common-0173e2f60b9cdf71cbe2.js``` now reachable!!! 🎉

but ```/``` not 😪

<img width="402" alt="image" src="https://user-images.githubusercontent.com/13001109/235333605-ce9516e6-1230-4b07-b8a0-51097d0eb466.png">


I think this is where the dog dug in
**/linuxserver/config/nginx/site-confs/default.conf**
```
    location / {
        try_files $uri @proxy;
    }
```

**Comment by thespad** [comment]
If your compose is accurate, then Traefik is going to be proxying to port 80, which will put you into an infinite redirect loop due to the Ruby backend forcing https.

**Comment by LuckyCoders** [comment]
```
#    labels:
#      - "traefik.http.services.foo.loadbalancer.serverstransport=ignorecert"
#      - "traefik.http.services.foo.loadbalancer.server.scheme=https"
```

I removed the traefik labels, but TOO_MANY_REDIRECTS remains

**Comment by LuckyCoders** [comment]
I replaced

```
    location / {
        try_files $uri @proxy;
    }
```

to

```
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://backend;
    }
```

in **/config/nginx/site-confs/default.conf**
and it's work!! 🎉

<img width="473" alt="Снимок экрана 2023-05-02 в 09 44 21" src="https://user-images.githubusercontent.com/13001109/235597865-9cf1a53d-bfef-4620-92c9-56225eebff8d.png">
