### ISSUE TITLE
Is it possible to implement params to enable translation

### ISSUE THREAD

**Issue by igisho** [linuxserver/docker-mastodon#64]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Mastodon implemented this: https://github.com/mastodon/mastodon/pull/19218

### Reason for change

It would be helpfull

### Proposed code change

Add enviroment variable with option to enable translation and api key for service.

**Comment by thespad** [comment]
It should just work, we pass all environment variables through to the application.

**Comment by YourAutisticLife** [comment]
Yes, it does work. In `docker-compose.yml`, for instance, you just need to set the `DEEPL` variables in your `environment` for mastodon:

```
    environment:
      - PUID=1000
      - PGID=1000
      [...]
      - DEEPL_API_KEY=[whatever]
      - DEPPL_PLAN=free
```
