### ISSUE TITLE
[FEAT] Add glitch-stable tag (or if glitch is intened to be stable, update tag creation rules)

### ISSUE THREAD

**Issue by eric-pierce** [linuxserver/docker-mastodon#78]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I use the glitch fork, but the glitch tag appears to include pre-releases (alpha releases, etc). The most recent working version of glitch is running v4.3.0-alpha.0+glitch

### Reason for change

I'd like the benefits of glitch, and of a stable system

### Proposed code change

Either update the glitch tag to only include stable mastodon, or add a glitch-stable branch/tag.

**Comment by thespad** [comment]
There isn't a Glitch stable for us to use, we build from the upstream [glitch-soc](https://github.com/glitch-soc/mastodon) repo which only provides commits - there are no tags or releases to base builds on. It is inherently an unstable fork.
